### PR TITLE
Create action to display test results on Github | test

### PR DESCRIPTION
**Pull request by justinchuby**
Use the `EnricoMi/publish-unit-test-result-action@v2` action to publish test results to GitHub. Example:

image

### CODE REVIEW

**Comment by justinchuby** [comment]
Nice errors:

image

**Comment by justinchuby** [comment]
@jcwchen could you take a look? Thanks!

**Comment by justinchuby** [comment]
After approval I will revert the test changes

**Review by jcwchen — APPROVED** [review]
Looks cool. Please revert them properly before merge.

**Pull request merged**
