### PR TITLE
Update links for renaming repository from onnx-script to onnxscript

### PR DESCRIPTION
**Pull request by abock**

### CODE REVIEW

**Review by gramalingam — APPROVED** [review]

**Comment by justinchuby** [comment]
We may need to coordinate renaming with the pytorch repo or the pytorch ci will start to fail

**Comment by justinchuby** [comment]
https://github.com/pytorch/pytorch/pull/99572

**Comment by justinchuby** [comment]
Fortunately github redirects the link. I think we are good

**Comment by jcwchen** [comment]
Please allow me to reopen this PR to re-trigger new Azurepipelines CI

**Review by jcwchen — APPROVED** [review]

**Comment by abock** [comment]
@justinchuby GitHub does a really good job of redirecting the old repo to the new across API endpoints, Git, and web.

**Pull request merged**
