### PR TITLE
[IR] Implement to_proto and from_proto convenience functions

### PR DESCRIPTION
**Pull request by justinchuby**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #1508

### CODE REVIEW

**Review by titaiwangms — COMMENTED** [review]
I feel they are overlapped ai with deserialize/serialize

**Comment by justinchuby** [comment]
This is a convenience for users to not have to decide which ser/de function to use. Any suggestions?

**Comment by titaiwangms** [comment]
> This is a convenience for users to not have to decide which ser/de function to use. Any suggestions?

Deprecate deserialize/serialize to avoid confusion? Having duplicated api seems weird.

**Review by titaiwangms — APPROVED** [review]
I think users would reference on how we use these api to start with. I suggest we keep one?

**Comment by justinchuby** [comment]
> > This is a convenience for users to not have to decide which ser/de function to use. Any suggestions?
> 
> Deprecate deserialize/serialize to avoid confusion? Having duplicated api seems weird.

But we still need the implementation somewhere. to/from_proto will pick a ser/de function. I agree we don't prefer duplication. Maybe we don't have to create to/from_proto?

**Comment by titaiwangms** [comment]
Maybe from original onnx user perspective, they would prefer apis with proto in names, so this is not a bad idea after all.
cc @gramalingam

**Comment by justinchuby** [comment]
@gramalingam I will merge if looks good to you?

**Review by shubhambhokare1 — APPROVED** [review]
lgtm! 
nit: Are these functions supposed to be for internal use? If these are to be exposed to user maybe adding a couple unit tests could be a good idea?

**Comment by justinchuby** [comment]
> lgtm! nit: Are these functions supposed to be for internal use? If these are to be exposed to user maybe adding a couple unit tests could be a good idea?

Yes, will do, thanks!

**Pull request merged**
