### PR TITLE
make shape inference optional due to segfault

### PR DESCRIPTION
**Pull request by wschin**
Although `onnx.shape_inference.infer_shapes` is put into try-except block, segfault still causes the entire program crashes. Making shape inference optional will be helpful if user hits segfault problem.

A segfault from PyTorch CI of my [PR](https://github.com/pytorch/pytorch/pull/106589) after upgrading onnxruntime=1.15.0 to onnxruntime-training=1.15.1,
image

### CODE REVIEW

**Comment by justinchuby** [comment]
If onnx segfaults i think we should fix onnx. I am a little worried that we are starting to grow the to_model_proto method. Ideally it mirrors onnxscript’s to_model_proto method which does not provide many options. 

Which version of ONNX is segfaulting? Could you share environment info? Thanks!

**Review by justinchuby — CHANGES_REQUESTED** [review]
Blocking for now. Thanks

**Comment by wschin** [comment]
This is one example --- https://github.com/pytorch/pytorch/actions/runs/5801748185/job/15727346375

I installed onnx-weekly first, then installed onnxruntime-training. Then my test hits segfault in to_model_proto. I guess segfault happens because onnxruntime-training overrides onnx-weekly with an earlier onnx.

**Comment by justinchuby** [comment]
I see. That could be possible. cc @jcwchen just in case this is a new segfault.

@wschin could you share the ONNX files so we can test that to make sure?

**Comment by wschin** [comment]
I guess it's related to onnx function. Maybe exporting this model with `dynamo_export` can just repro
```
        example_args_collection = tuple(
            (torch.randn(batch, 2, dtype=torch.float32),) for batch in (1, 2, 4, 6, 8)
        )

        class MLP(nn.Module):
            def __init__(self):
                super().__init__()
                self.fc1 = nn.Linear(2, 4, bias=True)
                self.fc2 = nn.Linear(4, 2, bias=True)

            def forward(self, tensor_x: torch.Tensor):
                tensor_x = self.fc1(tensor_x)
                tensor_x = torch.sigmoid(tensor_x)
                tensor_x = self.fc2(tensor_x)
                tensor_x = torch.sigmoid(tensor_x)
                return tensor_x
```

**Comment by justinchuby** [comment]
I tested with the latest onnx. Looks like no segfaults

**Comment by justinchuby** [comment]
with:

```python
for arg in example_args_collection: torch.onnx.dynamo_export(MLP(), *arg)
```

ONNX version 1.15.0.dev20230807

**Comment by justinchuby** [comment]
Also tested with ONNX 1.14.1

**Comment by justinchuby** [comment]
1.14 segfaults

**Comment by wschin** [comment]
Let's close it and open an issue to onnxruntime-training instead, because it sounds onnxruntime-training should fetch onnx-1.14.1 in its dep file. Many thanks.

**Pull request closed without merging**
