### PR TITLE
Add Op(built-in function ops) | feat(torchlib)

### PR DESCRIPTION
**Pull request by titaiwangms**
Fix https://github.com/microsoft/onnx-converters-private/issues/190

With https://github.com/pytorch/pytorch/pull/112758, this PR moves built-in function ops mapping into torchlib.
NOTE: module name of `operator.add` is _operator

### CODE REVIEW

**Comment by justinchuby** [comment]
LGTM. Cc @BowenBao for namespace naming conventions

**Comment by justinchuby** [comment]
I am thinking something like python.operator and python.math may be more principled

**Comment by titaiwangms** [comment]
> I am thinking something like python.operator and python.math may be more principled

A different domain from DOMAIN = "pkg.onnxscript.torch_lib"? I don't know if we should mark the difference in the graph, as they are the same (eg: operator.add and aten::add) in ONNX perspective.

**Comment by justinchuby** [comment]
I meant `python.operator::add` or `python.math::div`

**Comment by titaiwangms** [comment]
> I meant `python.operator::add` or `python.math::div` to denote they are python built-in values and avoid potential name conflicts (although unlikely)

In that case, string processing would need to live somewhere in torchlib registration or converter registration to match _operator.add (original name).

**Comment by justinchuby** [comment]
SG. That's a good argument to keep the existing names

**Review by justinchuby — APPROVED** [review]

**Pull request merged**
