### PR TITLE
Register `view_as_real` as complex functions | fix(torchlib)

### PR DESCRIPTION
**Pull request by justinchuby**
Previously I omitted `complex=True`

### CODE REVIEW

**Review by titaiwangms — APPROVED** [review]
Is there any test guarding it?

**Comment by justinchuby** [comment]
> Is there any test guarding it?

That’s a good question. I haven’t come up with ways of doing it. Any suggestions?

Will merge for now. Happy to follow up!

**Comment by titaiwangms** [comment]
> > Is there any test guarding it?
> 
> That’s a good question. I haven’t come up with ways of doing it. Any suggestions?
> 
> Will merge for now. Happy to follow up!

It can't be added into ops_test.py with extra_opinfo?

**Comment by justinchuby** [comment]
That's true. My bad

**Pull request merged**
