### PR TITLE
Allow including or excluding entire opsets from generation, remove Opset 19, 20 stubs

### PR DESCRIPTION
**Pull request by abock**
1. Add argument parsing for the opgen command. Adds the following options:
   ```
   usage: opgen [-h] [-x OPSET] [-i OPSET] [--min-opset-version MIN_OPSET_VERSION]

   options:
     -h, --help            show this help message and exit
     -x OPSET, --exclude OPSET
                           exclude an opset from generation; example: -x 19 -x
                           ai.onnx.ml/3
     -i OPSET, --include-only OPSET
                           include only these opsets; example: -i 19
     --min-opset-version MIN_OPSET_VERSION
                           the minimum supported ONNX opset version
   ```

   - If any `--include-only` opsets are specified, only those opsets will be included
   - `--exclude` opsets are then excluded

2. Add `OpsetsBuilder.Result` to hold state and summary information produced by the generation, and move the `write` method to this class.

3. Produce a nicer summary of the generation.

4. Drop Opsets 19 and 20 for now, since supporting these will require support for the new types across various other components (ONNX reference evaluator/numpy, ONNX Runtime):
   ```
   $ python -m opgen -x 19 -x 20             
   
   🎉 Generated Ops: 467
      Minimum Opset Version: 14
   
   🟢 Included Opsets:
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
      ai.onnx.ml/1, ai.onnx.ml/2, ai.onnx.ml/3,
      ai.onnx.preview.training/1
   
   🔴 Excluded Opsets:
      19, 20
   
   🟠 Unsupported Ops:
      reason: deprecated:
        - Upsample(10)
          https://onnx.ai/onnx/operators/onnx__Upsample.html#upsample-10
        - Scatter(11)
          https://onnx.ai/onnx/operators/onnx__Scatter.html#scatter-11
   ```

This should unblock #728 (to be rebased when this merges).

### CODE REVIEW

**Comment by abock** [comment]
It seems the failures are happening against PyTorch nightly builds, indicating maybe `torch.dtype` API has maybe changed?

```
onnxscript/tests/function_libs/torch_lib/ops_test.py::TestOutputConsistencyEagerCPU::test_output_match_opinfo__log_softmax_cpu_float32 - TypeError: argument of type 'torch.dtype' is not iterable
```

In any case, this should not be related to this PR.

**Review by gramalingam — APPROVED** [review]

**Comment by gramalingam** [comment]
> It seems the failures are happening against PyTorch nightly builds, indicating maybe `torch.dtype` API has maybe changed?
> 
> ```
> onnxscript/tests/function_libs/torch_lib/ops_test.py::TestOutputConsistencyEagerCPU::test_output_match_opinfo__log_softmax_cpu_float32 - TypeError: argument of type 'torch.dtype' is not iterable
> ```
> 
> In any case, this should not be related to this PR.

I guess that a single type is being specified where a list/tuple of types is expected. Eg., [this line](https://github.com/microsoft/onnxscript/blob/1681c242f60895e02970c9a47ba71ea547e36200/onnxscript/tests/function_libs/torch_lib/ops_test_data.py#L1478) looks like it is missing a comma to turn that into a tuple.

Not sure how this error creeped in originally.

**Comment by gramalingam** [comment]
@abock please feel free to merge it in, I wasn't sure if you were planning to make any changes.

**Comment by gramalingam** [comment]
Looks like the failures are from this merged PR: https://github.com/microsoft/onnxscript/pull/727

**Pull request merged**
