### PR TITLE
Fix Op(aten::_scaled_dot_product_efficient_attention) under fp16

### PR DESCRIPTION
**Pull request by BowenBao**
Insert castlike where needed.

### CODE REVIEW

**Comment by BowenBao** [comment]
Lint CI failing with `/opt/hostedtoolcache/Python/3.10.13/x64/bin/python: No module named lintrunner_adapters`. cc @justinchuby is there something I'm missing?

**Comment by BowenBao** [comment]
build_docs CI failing with
```
ERROR: Could not find a version that satisfies the requirement onnx-weekly==1.15.0.dev20230807 (from versions: 1.16.0.dev20231106, 1.16.0.dev20231113, 1.16.0.dev20231120, 1.16.0.dev20231127, 1.16.0.dev20231204)
ERROR: No matching distribution found for onnx-weekly==1.15.0.dev20230807
```

**Review by justinchuby — APPROVED** [review]

**Comment by justinchuby** [comment]
Fixing in https://github.com/microsoft/onnxscript/pull/1200

**Review by titaiwangms — APPROVED** [review]
Do we miss the fp16 tests?

**Comment by justinchuby** [comment]
Should `scale: FLOAT` be annotated differently?

**Comment by BowenBao** [comment]
> Should `scale: FLOAT` be annotated differently?

Maybe castlike earlier and update annotation. Those functions that are tagged as `private=True` won't ever be invoked from exporter op dispatcher directly right? So the scale is guaranteed to have been casted properly at that point.

**Pull request merged**
